// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * $Id$
 * Universidad Mariana (San Juan de Pasto - Colombia)
 * Programa Ingeniería de Sistemas
 * Licenciado bajo el esquema Academic Free License version 2.1 
 *
 * Análisis y modelamiento de software
 * Caso de estudio: Trazabilidad a la vacunación
 * Autor: Giovanni Hernández P. - 18-noviembre-2021
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
package syt_vacunacion.mundo;

import java.util.Date;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * $Id$
 * Universidad XX (San Juan de Pasto - Colombia)
 * Programa Ingeniería de Sistemas
 * Licenciado bajo el esquema Academic Free License version 2.1 
 *
 * Caso de estudio: Seguimiento y trazabilidad a la vacunación
 * Autor: Giovanni Hernández P. - 19-febrero-2022
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
public class Dosis {
	
	// - - - - - - - - - - - - - - - - - - - - - -
	// Constantes
	// - - - - - - - - - - - - - - - - - - - - - -
	
	/**
	 * Constante que representa la vacuna de Pfizer
	 */
	public final static String PFIZER = "pfizer";
	/**
	 * Constante que representa la vacuna de moderna
	 */
	public final static String MODERNA = "moderna";
	
	
	// - - - - - - - - - - - - - - - - - - - - - -
	// Atributos
	// - - - - - - - - - - - - - - - - - - - - - -
	/**
	 * El estudiante
	 */
	private Estudiante estudiante;
	
	/**
	 * La fecha de aplicación de la dosis
	 */
	private Date fecha;
	
	/**
	 * El tipo de vacuna que le aplicaron
	 */
	private String tipo;
	
	// - - - - - - - - - - - - - - - - - - - - - -
	// Métodos
	// - - - - - - - - - - - - - - - - - - - - - -

	/**
	 * Constructor de la clase Dosis
	 * @param estudiante El estudiante al que se le suministró la dosis estudiante!=null
	 * @param fecha La fecha de aplicación de la dosis fecha!=null
	 * @param tipo El tipo de dosis aplicada tipo!=""
	 */
	public Dosis(Estudiante estudiante, Date fecha, String tipo) {
		this.estudiante = estudiante;
		this.fecha = fecha;
		this.tipo = tipo;
	}

	/**
	 * Retorna el estudiante
	 * @return Devuelve el estudiante 
	 */
	public Estudiante darEstudiante() {
		return estudiante;
	}

	/**
	 * Modifica el estudiante
	 * @param estudiante El estudiante a modificar estudainte!=null
	 */
	public void modificarEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	/**
	 * Devuelve la fecha
	 * @return La fecha
	 */
	public Date darFecha() {
		return fecha;
	}

	/**
	 * Modifica la fecha
	 * @param fecha La fecha a modificar
	 */
	public void modificarFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * Devuelve el tipo de vacuna
	 * @return El tipo
	 */
	public String darTipo() {
		return tipo;
	}

	/**
	 * Modifica el tipo de vacuna
	 * @param tipo El tipo a modificar
	 */
	public void modificarTipo(String tipo) {
		this.tipo = tipo;
	}
	
};
