// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * $Id$
 * Universidad Mariana (San Juan de Pasto - Colombia)
 * Programa Ingeniería de Sistemas
 * Licenciado bajo el esquema Academic Free License version 2.1 
 *
 * Análisis y modelamiento de software
 * Caso de estudio: Trazabilidad a la vacunación
 * Autor: Giovanni Hernández P. - 18-noviembre-2021
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
package syt_vacunacion.mundo;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * $Id$
 * Universidad XX (San Juan de Pasto - Colombia)
 * Programa Ingeniería de Sistemas
 * Licenciado bajo el esquema Academic Free License version 2.1 
 *
 * Caso de estudio: Seguimiento y trazabilidad a la vacunación
 * Autor: Giovanni Hernández P. - 19-febrero-2022
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
public class Estudiante {
	
	// - - - - - - - - - - - - - - - - - - - - - -
	// Atributos
	// - - - - - - - - - - - - - - - - - - - - - -
	/**
	 * La identificación del estudiante 
	 */
	private String id;
	
	/**
	 * El nombre del estudiante
	 */
	private String nombre;
	
	/**
	 * El estado del estudiante en la Universidad (Matriculado si/no)
	 */
	private boolean estado;
	
	// - - - - - - - - - - - - - - - - - - - - - -
	// Métodos
	// - - - - - - - - - - - - - - - - - - - - - -
	/**
	 * Constructor de la clase estudiante
	 * @param id La identificación del estudiante id!=""
	 * @param nombre El nombre del estudiante nombre!=""
	 * @param estado El estado del estudainte estado=true || estado=false
	 */
	public Estudiante(String id, String nombre, boolean estado) {
		this.id = id;
		this.nombre = nombre;
		this.estado = estado;
	}

	/**
	 * Devuelve la identificación
	 * @return La identificación del estudiante
	 */
	public String darId() {
		return id;
	}

	/**
	 * Modifica la identificación
	 * @param id La identificación del estudiante
	 */
	public void modificarId(String id) {
		this.id = id;
	}

	/**
	 * Devuelve el nombre del estudiante
	 * @return El nombre del estudiante
	 */
	public String darNombre() {
		return nombre;
	}

	/**
	 * Modifica el nombre del estudiante
	 * @param nombre El nombre a modificar
	 */
	public void modificarNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Devuelve el estado del estudiante
	 * @return El estado
	 */
	public boolean darEstado() {
		return estado;
	}

	/**
	 * Modifica el estado del estudiante
	 * @param estado El estado a modificar
	 */
	public void modificarEstado(boolean estado) {
		this.estado = estado;
	}
	
	
};
